# Generated by Django 3.0.8 on 2020-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_words_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=20),
        ),
    ]
