# Generated by Django 3.0.8 on 2020-07-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200716_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
