# Generated by Django 3.0.8 on 2020-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200716_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
